<div class="fixed-action-btn horizontal">
    <a id="btncollapse" class="btn-floating btn-large tooltipped" data-position="left" data-delay="50" data-tooltip="APLICACIONES ARCADAT" data-activates="slide-out-user">
        <i class="material-icons">apps</i>
    </a>
</div>

<ul id="slide-out-user" class="side-nav">
    <li>
        <div class="userView">
            <div class="background">
                <img class="responsive-img" src="<?php echo $datos['person']['photo_person'] ?>"/>
            </div>
            <a href="#!user"><img class="circle" src="<?php echo $datos['person']['photo_person'] ?>"><span class="white-text name"><?php echo $datos['person']['first_name'] . '<br/>' . $datos['person']['last_name'] ?></span></a>
            <span class="white-text name">APLICACIONES ARCADAT ASOCIADAS</span>
        </div>
    </li>
    <?php if ($datos['settings']['is_user_admin'] == 'true'): ?>
    <li><a class="waves-effect" href="<?php echo $datos['settings']['link_admin']; ?>">Administración</a></li>
    <?php endif ?>
    <?php if ($datos['settings']['is_user_academic'] == 'true'): ?>
    <li><a class="waves-effect" href="<?php echo $datos['settings']['link_academic']; ?>">Coordinación Académica</a></li>
    <?php endif ?>
    <?php if ($datos['settings']['is_user_paysheet'] == 'true'): ?>
    <li><a class="waves-effect" href="<?php echo $datos['settings']['link_paysheet']; ?>">Nómina</a></li>
    <?php endif ?>
    <li><div class="divider"></div></li>
    <li><a class="waves-effect" href="/signout">Cerrar Sesión</a></li>
</ul>


<script type='text/javascript'>
    $("#btncollapse").sideNav();
    $('.tooltipped').tooltip();
</script>
