<div class="card">
    <div class="card-content">
        <div class="center">
            <img class="circle responsive-img activator" src="<?php echo $datos['person']['photo_person'] ?>"/>
        </div>
        <span class="card-title activator">
            <?php echo $datos['person']['first_name'] . ' ' . $datos['person']['last_name'] ?>
        </span>
        <p>
            <a href="#" data-activates="slide-out-user" class="btn button-collapse">Aplicaciones Arcadat</a>
        </p>
    </div>
</div>
