<div class="card">
    <div class="card-content">
        <div class="center-align">
            <img class="circle responsive-img activator" src="<?php echo $datos['photo_person'] ?>"/>
        </div>
        <div class="center-align">
            <span class="card-title activator"><?php echo $datos['first_name'] . ' ' . $datos['last_name'] ?></span>
        </div>
        <p class="center-align">
            <a href="/signout" data-activates="slide-out-user" class="btn button-collapse">Cerrar Sesión</a>
        </p>
    </div>
</div>
