<div class="card">
    <div class="card-content">
        <div class="center">
            <img class="circle responsive-img activator" src="<?php echo $datos['photo_person'] ?>"/>
        </div>
        <span class="card-title activator">
            <?php echo $datos['first_name'] . ' ' . $datos['last_name'] ?>
        </span>
        <p>
            <a href="#" data-activates="slide-out-user" class="btn button-collapse">Menú de Aplicaciones</a>
        </p>
    </div>
</div>

<ul id="slide-out-user" class="side-nav">
    <li>
        <div class="userView">
            <div class="background">
                <img class="responsive-img" src="<?php echo $datos['photo_person'] ?>"/>
            </div>
            <a href="#!user"><img class="circle" src="<?php echo $datos['photo_person'] ?>"></a>
            <a href="#!name"><span class="white-text name"><?php echo $datos['first_name'] . ' ' . $datos['last_name'] ?></span></a>
        </div>
    </li>
    <li><a class="waves-effect" href="#!">Aplicación Uno</a></li>
    <li><a class="waves-effect" href="#!">Aplicación Dos</a></li>
    <li><div class="divider"></div></li>
    <li><a class="waves-effect" href="#!">Cerrar Sesión</a></li>
</ul>


<script type='text/javascript'>
    $(".button-collapse").sideNav();
</script>
